color = ''
project-name = 'default'

[default]
account_id = 'acct_1SAWJbCrt2zrmIbK'
device_name = 'HANNU-P14s'
display_name = 'Haky76 sandbox'
test_mode_api_key = "PLACEHOLDER"
test_mode_key_expires_at = '2025-12-22'
test_mode_pub_key = "PLACEHOLDER"

